---
- name: Install OpenJDK
  yum: name=java state=present

- name: Install git
  yum: name=git state=present

- name: Install Ansible
  yum: name=ansible state=present

- name: Copy ansible.cfg
  copy: src=ansible.cfg dest=/etc/ansible
