---
- name: Copy the file for shard test
  template: src=test_data.j2 dest=/etc/ansible_setup/test_data.js

- name: copy the file enable sharding
  template: src=enable_sharding.j2 dest=/etc/ansible_setup/enable_sharding.js

- name: copy the file shard a collection
  template: src=shard_a_collection.j2 dest=/etc/ansible_setup/shard_a_collection.js

- name: Enable sharding on the database and collection
  command: mongo --port {{ mongos_port }} /etc/ansible_setup/enable_sharding.js

- name: Shard a Collection
  command: mongo {{ sharding_db }} --port {{ mongos_port }} /etc/ansible_setup/shard_a_collection.js

- name: Execute the collection creation script
  command: mongo {{ sharding_db }} --port {{ mongos_port }} /etc/ansible_setup/test_data.js
