---
# SHARD1
- name: create data directory for mongodb shard1
  file: path={{ mongodb_datadir_prefix }}/mongod/shard1/data state=directory owner=mongod group=mongod
  delegate_to: '{{ item }}'
  with_items: "{{ groups['mongod_servers'] }}"

- name: create log directory for mongodb shard1
  file: path={{ mongodb_datadir_prefix }}/mongod/shard1/log state=directory owner=mongod group=mongod

- name: create the mongodb shard1 configuration file
  template: src=mongod-shard1.conf.j2 dest=/etc/mongod-shard1.conf
  delegate_to: '{{ item }}'
  with_items: "{{ groups['mongod_servers'] }}"

- name: start the mongodb shard1 service
  command: mongod --config /etc/mongod-shard1.conf

# SHARD2
- name: create data directory for mongodb shard2
  file: path={{ mongodb_datadir_prefix }}/mongod/shard2/data state=directory owner=mongod group=mongod
  delegate_to: '{{ item }}'
  with_items: "{{ groups['mongod_servers'] }}"

- name: create log directory for mongodb shard2
  file: path={{ mongodb_datadir_prefix }}/mongod/shard2/log state=directory owner=mongod group=mongod

- name: create the mongodb shard2 configuration file
  template: src=mongod-shard2.conf.j2 dest=/etc/mongod-shard2.conf
  delegate_to: '{{ item }}'
  with_items: "{{ groups['mongod_servers'] }}"

- name: start the mongodb shard2 service
  command: mongod --config /etc/mongod-shard2.conf

# SHARD3
- name: create data directory for mongodb shard3
  file: path={{ mongodb_datadir_prefix }}/mongod/shard3/data state=directory owner=mongod group=mongod
  delegate_to: '{{ item }}'
  with_items: "{{ groups['mongod_servers'] }}"

- name: create log directory for mongodb shard3
  file: path={{ mongodb_datadir_prefix }}/mongod/shard3/log state=directory owner=mongod group=mongod

- name: create the mongodb shard3 configuration file
  template: src=mongod-shard3.conf.j2 dest=/etc/mongod-shard3.conf
  delegate_to: '{{ item }}'
  with_items: "{{ groups['mongod_servers'] }}"

- name: start the mongodb shard3 service
  command: mongod --config /etc/mongod-shard3.conf
