---
- name: Copy mongodb initial setup
  template: src=mongodb_replset_init.js.j2 dest=/tmp/ansible_setup/mongodb_replset_init.js owner=root group=root mode=0644

- name: Initiate the replica set
  command: mongo /tmp/ansible_setup/mongodb_replset_init.js
  when: ansible_hostname.endswith("test01")
