---
- name: 配置Nginx官方源
  copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo

- name: Install nginx
  yum: name=nginx state=latest

- name: 创建Nginx的Web文件目录
  file: path={{ nginx_html_dir }} state=directory owner=nginx group=nginx

- name: 创建Nginx的Log文件目录
  file: path={{ nginx_log_dir }} state=directory owner=nginx group=nginx

- name: Copy nginx config
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Copy nginx vhost config
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: Start Nginx Service
  service: name=nginx state=started enabled=yes
