---
- name: 配置PHP 5.6安装包源
  yum: name=http://mirror.webtatic.com/yum/el6/latest.rpm state=present

- name: Install PHP 5.6
  yum: name={{ item }} state=present enablerepo=webtatic
  with_items:
    - php56w.x86_64
    - php56w-devel
    - php56w-gd.x86_64
    - php56w-ldap.x86_64
    - php56w-mbstring.x86_64
    - php56w-mcrypt.x86_64
    - php56w-mysql.x86_64
    - php56w-pdo.x86_64 
    - php56w-opcache.x86_64

- name: Install PHP FPM
  yum: name=php56w-fpm state=present enablerepo=webtatic

- name: 启动php-fpm
  service: name=php-fpm state=started enabled=yes
