---
- name: Copy MySQL Security script to client
  template: src=mysql_security.sh.j2 dest=/tmp/mysql_security.sh owner=root group=root mode=0755

- name: Run MySQL Security script
  shell: /bin/bash /tmp/mysql_security.sh

- name: Create test database
  mysql_db: login_user=root login_password={{ mysql_root_password }} name={{ db_name }} state=present

- name: Create test database user
  mysql_user: login_user=root login_password={{ mysql_root_password }} name={{ db_user }} password={{ db_password }} priv=*.*:ALL host='%' state=present
